### ISSUE TITLE
Can we provide a makefile with different targets? 

### ISSUE THREAD

**Issue by MrPowers** [delta-incubator/dat#2]
Can we provide a makefile with different targets?  

_Originally posted by @edmondo1984 in https://github.com/delta-incubator/dat/pull/1#discussion_r946917436_

**Comment by edmondo1984** [comment]
```
.PHONY: create-tables
create-tables:
        poetry run python -m tables.create_tables    
```

or something like that would work

**Comment by MrPowers** [comment]
We're doing this in #4
